# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-21 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20191218_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_time', models.DateTimeField()),
                ('h_user_index', models.IntegerField()),
                ('h_index', models.IntegerField()),
                ('handle', models.CharField(max_length=512)),
                ('h_user_login', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_time', models.DateTimeField()),
                ('l_ip', models.CharField(max_length=16)),
                ('l_user', models.CharField(max_length=64)),
            ],
        ),
    ]
